### PR TITLE
KOGITO-241 Add commons-lang3 to dependencies

### PR DESCRIPTION
**Pull request by baldimir**
Related -runtimes PR: https://github.com/kiegroup/kogito-runtimes/pull/147
(should be merged together)

### CODE REVIEW

**Comment by mswiderski** [comment]
@baldimir I quickly looked at the other PR but I don't see any use of commans-lang in the code except it being defined in pom. Is this really needed?

**Comment by baldimir** [comment]
@mswiderski it is used here https://github.com/kiegroup/kogito-runtimes/pull/147/files#diff-41e83d08d000bcfcccf2ae574d45d5a2R759. However if you think it would be better without the dependency, I can remove it. I used it just so the method used is better than just using the JVM OS system property directly.

**Comment by mswiderski** [comment]
@baldimir I'd prefer to avoid adding dependencies just for such usage... it comes with transitive reps as well so unless we have more use of it then we could add, wdyt?

**Comment by baldimir** [comment]
Ok, makes sense. So closing this.

**Pull request closed without merging**
