### PR TITLE
OptaPlanner wrapper (initial implementation)

### PR DESCRIPTION
**Pull request by ge0ffrey**
Required for https://github.com/kiegroup/kogito-runtimes/pull/216

### CODE REVIEW

**Comment by ge0ffrey** [comment]
jenkins retest this

**Comment by ge0ffrey** [comment]
jenkins test

**Comment by ge0ffrey** [comment]
jenkins retest this please
pretty please?

**Comment by ge0ffrey** [comment]
jenkins please retest this

**Comment by ge0ffrey** [comment]
@mswiderski This failure is a false negative: this PR ran the example same full build and it was green: https://github.com/kiegroup/kogito-runtimes/pull/216
But jenkins doesn't seem to want to do it again.

**Comment by mswiderski** [comment]
@ge0ffrey I restarted the build to rerun it so let's wait for the build to complete

**Review by mswiderski — APPROVED** [review]

**Pull request merged**
