### PR TITLE
make kogito's snapshot to depend on snapshots of drools and jbpm

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by mswiderski** [comment]
please don't merge this until we do 0.7.1

**Comment by mswiderski** [comment]
@mareknovotny I don’t think I am the best person to approve it as I disagree with this v7 to kogito relationship

**Comment by cristianonicolai** [comment]
@mariofusco wouldn't this mean that Kogito would now become a downstream build of v7?

**Comment by mareknovotny** [comment]
@mswiderski that's fair, but I am against this TOO. There should be only **FINAL** versions referenced .

I would like to avoid that someone will merge this without proper review process and if we agree in majority it if NOT what we want there will be a record of discussion here ;)

**Comment by mariofusco** [comment]
I was depending from SNAPSHOTs for continuous integration reasons as also suggested by @krisv (see email thread "Sync'ing drools-model between drools and kogito codebases"). I agree there're pros and cons with both situations and a perfect solution doesn't exist.

I will close this PR, move the bom back into kogito-runtimes (@mswiderski @cristianonicolai @mareknovotny do we all agree with this?) and add a profile that depends on snapshot so we could possibly use this profile for local testing and CI.

**Comment by mareknovotny** [comment]
I am ok with moving kogito-bom into kogito-runtimes.
I am not sure if having profile for FINAL and SNAPSHOT version in pom.xml directly is a good way.

if that is just for CI, we can have a script which modifies a version property and run the build - locally or in CI.

**Pull request closed without merging**
