### PR TITLE
KOGITO-105 - Upgrade Kogito Runtimes to Quarkus 0.21.1

### PR DESCRIPTION
**Pull request by mswiderski**
@ricardozanini @cristianonicolai here is a PR to upgrade Quarkus, would you mind trying our few examples to see if there are no issues? I will do that myself in the evening too, but just to have additional people verifying that.

@ricardozanini this will need to upgrade GraalVM in the images as well.

@spolti fyi

### CODE REVIEW

**Comment by ricardozanini** [comment]
@mswiderski I'll try to run the onboarding examples with the CLI and the Operator with a s2i updated with the new GraalVM.

**Comment by ricardozanini** [comment]
Will this be merged for 0.3?

**Comment by mswiderski** [comment]
Assuming we verify it works well then I think it should go into 0.3. Anything against it?

**Comment by ricardozanini** [comment]
Not on my side, no. It's a pain to build images to test the examples with PRs though... I'm still getting there :D

**Comment by mswiderski** [comment]
ok, I tested jbpm-quarkus-example and complete onboarding with native image build with quarkus 0.21.1 and GraalVM 19.1.1 all works fine. So from my end it looks good to be merged for 0.3.0 release

**Comment by ricardozanini** [comment]
All fine here:

```
I0821 17:32:55.124303   16268 sti.go:679] [INFO] --- quarkus-maven-plugin:0.21.1:native-image (default) @ onboarding ---
I0821 17:32:55.129991   16268 sti.go:679] [INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on OpenJDK 64-Bit GraalVM CE 19.1.1
```

```
2019-08-21 20:49:49,903 DEBUG [org.kie.kog.clo.wor.ser.dis.BaseServiceDiscovery] (executor-thread-1) About to query for endpoints in namespace kogito with labels employeeValidation:null
2019-08-21 20:49:49,903 DEBUG [org.kie.kog.clo.kub.cli.ope.BaseOperations] (executor-thread-1) About to query the Kubernetes API with url https://172.30.0.1:443/api/v1/namespaces/kogito/services?labelSelector=employeeValidation with label selector {employeeValidation=null} in namespace  'kogito'
2019-08-21 20:49:49,907 DEBUG [org.kie.kog.clo.kub.cli.ope.BaseOperations] (executor-thread-1) Response Headers received from the Kube cluster: Audit-Id: 52c8cb28-77b8-40cc-8263-57d59593b7e6
Cache-Control: no-store
Content-Type: application/json
Date: Wed, 21 Aug 2019 20:49:49 GMT
Content-Length: 789

2019-08-21 20:49:49,907 DEBUG [org.kie.kog.clo.kub.cli.ope.BaseOperations] (executor-thread-1) Received response data from Kube API: {"kind":"ServiceList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/namespaces/kogito/services","resourceVersion":"3971278"},"items":[{"metadata":{"name":"hr-service","namespace":"kogito","selfLink":"/api/v1/namespaces/kogito/services/hr-service","uid":"a9d18470-a7ce-11e9-8614-0615e4bfa428","resourceVersion":"144898","creationTimestamp":"2019-07-16T13:36:06Z","labels":{"app":"hr-service","department":"process","employeeValidation":"process","id":"process"}},"spec":{"ports":[{"name":"8080-tcp","protocol":"TCP","port":8080,"targetPort":8080}],"selector":{"app":"hr-service","department":"process","deploymentconfig":"hr-service","employeeValidation":"process","id":"process"},"clusterIP":"172.30.230.90","type":"ClusterIP","sessionAffinity":"None"},"status":{"loadBalancer":{}}}]}
```

What a day!! \o/

**Comment by cristianonicolai** [comment]
@mswiderski Im running tests locally, will let you know but if you can please rebase your change, that will add the latest changes from data index into the build check as well.

**Comment by cristianonicolai** [comment]
@mswiderski ok so for native I ran into the same issue as @ricardozanini on Fedora: https://github.com/oracle/graal/issues/1582. Not related to this updated but couldn't verify it.

Data Index seems to be working fine as well.

If I try to run the jbpm-quarkus-example on dev mode and persistence, test fails: https://gist.github.com/cristianonicolai/f6e7c0790694054682fc3ba8648b0ce1 and running: https://gist.github.com/cristianonicolai/aa798a5bd13ad6c3a7d1609ffbcb63f9

running the jbpm-quarkus-example-8.0.0-SNAPSHOT-runner.jar with persistence enabled works fine.

**Comment by mswiderski** [comment]
@cristianonicolai rebased and investigated the problem. Main issue is that the quarkus test does not take into account profile dependencies so moving the dependencies to main section allows to run them. Though I found one issue https://issues.jboss.org/browse/KOGITO-173 and fix is coming...
I don't think there are any blockers for the quarkus version upgrade.

**Comment by ricardozanini** [comment]
The GraalVM issue is really sad, but should be solved in a minor after 19.2.0 (released yesterday). I’m afraid our images could face this issue if the ubi8 got updated. Maybe worth a 0.3.1 if Quarkus and GraalVM coordinate this fix before our 0.4.

**Review by cristianonicolai — APPROVED** [review]

**Comment by mswiderski** [comment]
@ricardozanini you’re good for this to be merged?

**Comment by ricardozanini** [comment]
@mswiderski go ahead!!

**Comment by mswiderski** [comment]
Looks like next version of Quarkus will have 19.2.0 support so we can wait with image push if needed and upgrade to 19.2 if needed

https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!msg/quarkus-dev/EqQLEkZ5LYI/XjNCaawHAgAJ

**Comment by ricardozanini** [comment]
Awesome! Thanks for sharing this info, @mswiderski

**Pull request merged**
