### PR TITLE
DROOLS-4038: Migrate Runtimes > API modules to JUnit 5

### PR DESCRIPTION
**Pull request by triceo**
Merge with https://github.com/kiegroup/submarine-runtimes/pull/48

### CODE REVIEW

**Comment by triceo** [comment]
@mariofusco @mswiderski Please review.

There will be plenty PRs from me, similar to this one. If you don't wish to deal with them, please designate someone else to review them, perhaps @baldimir ?

**Comment by evacchi** [comment]
I am assigning @baldimir :)

**Review by mswiderski — APPROVED** [review]
looks ok to me

**Comment by mswiderski** [comment]
@triceo just one comment, please add all PRs that should be merged in the description of the PR so we won't miss anything, thanks for doing the upgrade!

**Pull request merged**
